//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class CustomerUser
    {
        public int CustomerUserId { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual WFSUser WFSUser { get; set; }
    }
    
}
