//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerUsers = new HashSet<CustomerUser>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string CustomerType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExt { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CustomerUser> CustomerUsers { get; set; }
    }
    
}
