//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class DaysOff
    {
        public DaysOff()
        {
            this.SchoolDaysOffs = new HashSet<SchoolDaysOff>();
        }
    
        public int DaysOffId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<System.DateTime> RangeStart { get; set; }
        public Nullable<System.DateTime> RangeEnd { get; set; }
    
        public virtual ICollection<SchoolDaysOff> SchoolDaysOffs { get; set; }
    }
    
}
