//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class FoodCategory
    {
        public FoodCategory()
        {
            this.FoodItems = new HashSet<FoodItem>();
        }
    
        public int FoodCategoryId { get; set; }
        public string Name { get; set; }
        public int VendorID { get; set; }
        public string CategoryType { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<FoodItem> FoodItems { get; set; }
    }
    
}
