//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class FoodItem
    {
        public FoodItem()
        {
            this.FoodItemOptions = new HashSet<FoodItemOption>();
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public int FoodItemId { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
        public int VendorFoodCategoryID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<FoodItemOption> FoodItemOptions { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual VendorFoodCategory VendorFoodCategory { get; set; }
    }
    
}
