//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class Menu
    {
        public Menu()
        {
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public int MenuId { get; set; }
        public int VendorId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
    }
    
}
