//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderItemOptions = new HashSet<OrderItemOption>();
        }
    
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int FoodItemId { get; set; }
        public int OrderProfileId { get; set; }
        public bool IsCancelled { get; set; }
        public decimal PriceCharged { get; set; }
        public System.DateTime DeliveryDate { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual Order Order { get; set; }
        public virtual UserOrderProfile UserOrderProfile { get; set; }
        public virtual ICollection<OrderItemOption> OrderItemOptions { get; set; }
    }
    
}
