//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class School
    {
        public School()
        {
            this.DaysOffs = new HashSet<DaysOff>();
            this.LunchPeriods = new HashSet<LunchPeriod>();
            this.SchoolGrades = new HashSet<SchoolGrade>();
            this.Teachers = new HashSet<Teacher>();
            this.UserOrderProfiles = new HashSet<UserOrderProfile>();
        }
    
        public int SchoolId { get; set; }
        public System.TimeSpan DeliveryTime { get; set; }
    
        public virtual ICollection<DaysOff> DaysOffs { get; set; }
        public virtual ICollection<LunchPeriod> LunchPeriods { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<SchoolGrade> SchoolGrades { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<UserOrderProfile> UserOrderProfiles { get; set; }
    }
    
}
