//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class StoreUser
    {
        public int StoreUserId { get; set; }
        public int StoreId { get; set; }
        public int UserId { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual WFSUser WFSUser { get; set; }
    }
    
}
