//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class Store
    {
        public Store()
        {
            this.StoreUsers = new HashSet<StoreUser>();
        }
    
        public int StoreId { get; set; }
        public int VendorId { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExt { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<StoreUser> StoreUsers { get; set; }
    }
    
}
