//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class Teacher
    {
        public Teacher()
        {
            this.SchoolTeachers = new HashSet<SchoolTeacher>();
        }
    
        public int TeacherId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SchoolTeacher> SchoolTeachers { get; set; }
    }
    
}
