//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class Vendor
    {
        public Vendor()
        {
            this.FoodCategories = new HashSet<FoodCategory>();
            this.FoodOptions = new HashSet<FoodOption>();
            this.Menus = new HashSet<Menu>();
            this.Stores = new HashSet<Store>();
            this.VendorUsers = new HashSet<VendorUser>();
        }
    
        public int VendorId { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExt { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<FoodCategory> FoodCategories { get; set; }
        public virtual ICollection<FoodOption> FoodOptions { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
        public virtual ICollection<VendorUser> VendorUsers { get; set; }
    }
    
}
