//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WFS.DataContext
{
    public partial class WFSUser
    {
        public WFSUser()
        {
            this.CustomerUsers = new HashSet<CustomerUser>();
            this.StoreUsers = new HashSet<StoreUser>();
            this.VendorUsers = new HashSet<VendorUser>();
        }
    
        public int UserId { get; set; }
        public System.Guid MembershipGuid { get; set; }
        public string UserType { get; set; }
        public decimal AvailableCredit { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<CustomerUser> CustomerUsers { get; set; }
        public virtual ICollection<StoreUser> StoreUsers { get; set; }
        public virtual ICollection<VendorUser> VendorUsers { get; set; }
        public virtual WFSUserAddress WFSUserAddress { get; set; }
    }
    
}
